命令执行

 

超时：有一个定时任务线程的不断的去检查状态，如果在超时时间之前，命令执行完了，此时会清理掉那个定时任务，命令的timeout state => COMPLETED

 

异常：命令执行的过程中，报错了，抛异常了，异常肯定会不断的抛出来，给别人去处理

 

拒绝：等待队列满，线程池，抛异常

 

共同的一个特点，都是在抛出这个异常，我们想，抛出异常的话呢，肯定会让别人去处理，肯定有个人会去处理你异常的情况，然后执行你的fallback降级逻辑



fallback降级逻辑是在哪儿执行的？？？

 com.netflix.hystrix.AbstractCommand.HystrixObservableTimeoutOperator<R>

executeCommandAndObserve()



新版本   getFallbackOrThrowException()

com.netflix.hystrix.HystrixCommand.getFallbackObservable()   降级逻辑

```

 

​    final Func1<Throwable, Observable<R>> handleFallback = new Func1<Throwable, Observable<R>>() {

​      @Override

​      public Observable<R> call(Throwable t) {

​        circuitBreaker.markNonSuccess();

​        Exception e = getExceptionFromThrowable(t);

​        executionResult = executionResult.setExecutionException(e);

​        if (e instanceof RejectedExecutionException) {

​          return handleThreadPoolRejectionViaFallback(e);

​        } else if (t instanceof HystrixTimeoutException) {

​          return handleTimeoutViaFallback();

​        } else if (t instanceof HystrixBadRequestException) {

​          return handleBadRequestByEmittingError(e);

​        } else {

​          /*

​           \* Treat HystrixBadRequestException from ExecutionHook like a plain HystrixBadRequestException.

​           */

​          if (e instanceof HystrixBadRequestException) {

​            eventNotifier.markEvent(HystrixEventType.BAD_REQUEST, commandKey);

​            return Observable.error(e);

​          }

 

​          return handleFailureViaFallback(e);

​        }

​      }

​    };

 
```

你会发现所有的异常，都会交给handleFallback来处理，针对不同的异常，reject、timeout、failure，拒绝、超时、失败，都会执行降级逻辑







